import { generateId } from '@/utils';
import { Question } from '@/types';

export interface QuizTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  subcategory: string;
  questions: Omit<Question, 'id' | 'createdAt' | 'updatedAt' | 'gameId'>[];
}

export const QUIZ_TEMPLATES: QuizTemplate[] = [
  {
    id: 'jomon-period',
    title: '縄文時代',
    description: '土器の出現から定住生活の始まりまで、縄文時代の特徴を学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '縄文時代に使われていた、表面に縄の目の文様がある土器を何といいますか？',
        choices: [
          { id: generateId(), text: '縄文土器', isCorrect: true },
          { id: generateId(), text: '弥生土器', isCorrect: false },
          { id: generateId(), text: '須恵器', isCorrect: false },
          { id: generateId(), text: '土師器', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '縄文土器は、厚手で黒褐色、低温で焼かれているのが特徴です。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '縄文時代の人々が住んでいた、地面を掘り下げて床にした住居を何といいますか？',
        choices: [
          { id: generateId(), text: '竪穴住居', isCorrect: true },
          { id: generateId(), text: '高床倉庫', isCorrect: false },
          { id: generateId(), text: '寝殿造', isCorrect: false },
          { id: generateId(), text: '書院造', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '竪穴住居は、半地下構造で保温性に優れていました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'yayoi-period',
    title: '弥生時代',
    description: '稲作の伝来と金属器の使用、ムラからクニへの変化を学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '弥生時代に大陸から伝わり、生活を大きく変えた農業は何ですか？',
        choices: [
          { id: generateId(), text: '稲作（水田稲作）', isCorrect: true },
          { id: generateId(), text: '畑作', isCorrect: false },
          { id: generateId(), text: '果樹栽培', isCorrect: false },
          { id: generateId(), text: '酪農', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '稲作の伝来により、定住生活がより安定し、余剰生産物による貧富の差が生まれました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '中国の歴史書「魏志倭人伝」に記されている、邪馬台国の女王は誰ですか？',
        choices: [
          { id: generateId(), text: '卑弥呼', isCorrect: true },
          { id: generateId(), text: '持統天皇', isCorrect: false },
          { id: generateId(), text: '北条政子', isCorrect: false },
          { id: generateId(), text: '推古天皇', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '卑弥呼は30余りのクニをまとめ、魏から「親魏倭王」の称号と金印を授かりました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'kofun-period',
    title: '古墳時代',
    description: '巨大な前方後円墳とヤマト王権の成立について学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '古墳時代に造られた、円形と方形を組み合わせた日本独特の形の古墳を何といいますか？',
        choices: [
          { id: generateId(), text: '前方後円墳', isCorrect: true },
          { id: generateId(), text: '円墳', isCorrect: false },
          { id: generateId(), text: '方墳', isCorrect: false },
          { id: generateId(), text: '八角墳', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '前方後円墳は、ヤマト王権の影響力が及んだ範囲に広がっています。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '古墳の周囲や頂上に並べられた、素焼きの土製品を何といいますか？',
        choices: [
          { id: generateId(), text: '埴輪', isCorrect: true },
          { id: generateId(), text: '土偶', isCorrect: false },
          { id: generateId(), text: '銅鐸', isCorrect: false },
          { id: generateId(), text: '勾玉', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '埴輪には家、馬、人などの形があり、当時の生活を知る手がかりになります。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'asuka-period',
    title: '飛鳥時代',
    description: '聖徳太子の政治から大化の改新まで、律令国家への歩みを学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '推古天皇の摂政となり、冠位十二階や十七条の憲法を定めた人物は誰ですか？',
        choices: [
          { id: generateId(), text: '聖徳太子（厩戸王）', isCorrect: true },
          { id: generateId(), text: '中大兄皇子', isCorrect: false },
          { id: generateId(), text: '中臣鎌足', isCorrect: false },
          { id: generateId(), text: '蘇馬入鹿', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '聖徳太子は仏教を厚く信じ、法隆寺を建立するなど文化の発展にも尽力しました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '645年、中大兄皇子らが蘇我氏を倒して始めた政治改革を何といいますか？',
        choices: [
          { id: generateId(), text: '大化の改新', isCorrect: true },
          { id: generateId(), text: '壬申の乱', isCorrect: false },
          { id: generateId(), text: '承久の乱', isCorrect: false },
          { id: generateId(), text: '明治維新', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '大化の改新により、土地と人民を国家のものとする公地公民の制が目指されました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'nara-period',
    title: '奈良時代',
    description: '平城京を中心に栄えた天平文化と、律令制度の確立を学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '710年、唐の長安にならって奈良に造られた都を何といいますか？',
        choices: [
          { id: generateId(), text: '平城京', isCorrect: true },
          { id: generateId(), text: '平安京', isCorrect: false },
          { id: generateId(), text: '藤原京', isCorrect: false },
          { id: generateId(), text: '難波京', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '平城京は、碁盤の目のように区画された美しい都でした。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '聖武天皇が国ごとに建てさせた、仏教の力で国を守るための寺を何といいますか？',
        choices: [
          { id: generateId(), text: '国分寺', isCorrect: true },
          { id: generateId(), text: '東大寺', isCorrect: false },
          { id: generateId(), text: '興福寺', isCorrect: false },
          { id: generateId(), text: '唐招提寺', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '聖武天皇は東大寺に大仏を造り、全国に国分寺・国分尼寺を建立しました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'heian-period',
    title: '平安時代',
    description: '藤原氏の摂関政治と、国風文化の発展について学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '平安時代、藤原氏が娘を天皇のきさきにして権力を握った政治を何といいますか？',
        choices: [
          { id: generateId(), text: '摂関政治', isCorrect: true },
          { id: generateId(), text: '院政', isCorrect: false },
          { id: generateId(), text: '執権政治', isCorrect: false },
          { id: generateId(), text: '武家政治', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '藤原道長・頼通の親子が、摂関政治の全盛期を築きました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '紫式部によって書かれた、平安時代の貴族の生活を描いた長編物語は何ですか？',
        choices: [
          { id: generateId(), text: '源氏物語', isCorrect: true },
          { id: generateId(), text: '枕草子', isCorrect: false },
          { id: generateId(), text: '竹取物語', isCorrect: false },
          { id: generateId(), text: '平家物語', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '源氏物語は、かな文字で書かれた世界最古級の長編小説です。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'kamakura-period',
    title: '鎌倉時代',
    description: '源頼朝による武家政権の誕生と、元寇の試練を学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '1192年、征夷大将軍に任命され鎌倉幕府を開いた人物は誰ですか？',
        choices: [
          { id: generateId(), text: '源頼朝', isCorrect: true },
          { id: generateId(), text: '源義経', isCorrect: false },
          { id: generateId(), text: '北条時宗', isCorrect: false },
          { id: generateId(), text: '足利尊氏', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '源頼朝は、平氏を倒した後、日本で最初の本格的な武家政権を樹立しました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '13世紀後半、モンゴル帝国（元）が2度にわたって日本に攻めてきた出来事を何といいますか？',
        choices: [
          { id: generateId(), text: '元寇', isCorrect: true },
          { id: generateId(), text: '白村江の戦い', isCorrect: false },
          { id: generateId(), text: '刀伊の入寇', isCorrect: false },
          { id: generateId(), text: '応仁の乱', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '元寇（文永の役・弘安の役）では、鎌倉武士が激しく抵抗し、暴風雨の助けもあり元軍を退けました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'nanbokucho-period',
    title: '南北朝時代',
    description: '後醍醐天皇の建武の新政と、2つの朝廷が並立した時代を学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '鎌倉幕府を倒した後、後醍醐天皇が行った天皇中心の新しい政治を何といいますか？',
        choices: [
          { id: generateId(), text: '建武の新政', isCorrect: true },
          { id: generateId(), text: '寛政の改革', isCorrect: false },
          { id: generateId(), text: '天保の改革', isCorrect: false },
          { id: generateId(), text: '享保の改革', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '建武の新政は、武士の不満を買い、わずか2年余りで崩壊しました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '後醍醐天皇が逃れた吉野の朝廷（南朝）に対し、足利尊氏が京都に立てた朝廷を何といいますか？',
        choices: [
          { id: generateId(), text: '北朝', isCorrect: true },
          { id: generateId(), text: '西朝', isCorrect: false },
          { id: generateId(), text: '東朝', isCorrect: false },
          { id: generateId(), text: '新朝', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '約60年間にわたり、京都の北朝と吉野の南朝が対立し続けました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'muromachi-period',
    title: '室町時代',
    description: '足利氏の幕府と、金閣・銀閣に代表される文化を学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '室町幕府三代将軍で、南北朝の合一を果たし、京都に金閣を建てた人物は誰ですか？',
        choices: [
          { id: generateId(), text: '足利義満', isCorrect: true },
          { id: generateId(), text: '足利義政', isCorrect: false },
          { id: generateId(), text: '足利尊氏', isCorrect: false },
          { id: generateId(), text: '足利義昭', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '足利義満は、明との勘合貿易を始め、幕府の権威を高めました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '1467年、将軍の世継ぎ争いから始まり、11年間も続いた戦乱を何といいますか？',
        choices: [
          { id: generateId(), text: '応仁の乱', isCorrect: true },
          { id: generateId(), text: '保元の乱', isCorrect: false },
          { id: generateId(), text: '平治の乱', isCorrect: false },
          { id: generateId(), text: '観応の擾乱', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '応仁の乱により京都は荒廃し、下剋上の風潮が広まって戦国時代へと突入しました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'sengoku-period',
    title: '戦国時代',
    description: '下剋上の世の中と、各地で勢力を競った戦国大名について学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '下の者が上の者を実力で倒す、戦国時代の風潮を何といいますか？',
        choices: [
          { id: generateId(), text: '下剋上', isCorrect: true },
          { id: generateId(), text: '封建制', isCorrect: false },
          { id: generateId(), text: '実力主義', isCorrect: false },
          { id: generateId(), text: '御恩と奉公', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '下剋上により、身分が低くても実力があれば大名になれる時代となりました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '戦国大名が領地を治めるために独自に定めた法律を何といいますか？',
        choices: [
          { id: generateId(), text: '分国法', isCorrect: true },
          { id: generateId(), text: '公事方御定書', isCorrect: false },
          { id: generateId(), text: '御成敗式目', isCorrect: false },
          { id: generateId(), text: '十七条の憲法', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '分国法は、領国内の武士や民衆を統制するために作られました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'azuchi-momoyama-period',
    title: '安土桃山時代',
    description: '織田信長と豊臣秀吉による天下統一の歩みを学びます。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '楽市・楽座や関所の廃止を行い、経済を活性化させた戦国武将は誰ですか？',
        choices: [
          { id: generateId(), text: '織田信長', isCorrect: true },
          { id: generateId(), text: '豊臣秀吉', isCorrect: false },
          { id: generateId(), text: '武田信玄', isCorrect: false },
          { id: generateId(), text: '上杉謙信', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '織田信長は、既存の特権を排除し、自由な商売を認めることで城下町を繁栄させました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '豊臣秀吉が全国の田畑を調査し、収穫量を石高で表した政策を何といいますか？',
        choices: [
          { id: generateId(), text: '太閤検地', isCorrect: true },
          { id: generateId(), text: '刀狩', isCorrect: false },
          { id: generateId(), text: '検地', isCorrect: false },
          { id: generateId(), text: '地租改正', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '太閤検地と刀狩により、武士と農民の身分をはっきり分ける「兵農分離」が進みました。',
        imageUrl: null,
        order: 1,
      },
    ],
  },
  {
    id: 'edo-period-review',
    title: '江戸時代の総復習',
    description: '中学校の歴史で習う江戸時代の政治、外交、文化、人物を網羅した復習テストです。',
    category: '社会',
    subcategory: '歴史',
    questions: [
      {
        type: 'multiple-choice',
        text: '1603年、江戸幕府を開き初代将軍となった人物は誰ですか？',
        choices: [
          { id: generateId(), text: '徳川家康', isCorrect: true },
          { id: generateId(), text: '徳川家光', isCorrect: false },
          { id: generateId(), text: '織田信長', isCorrect: false },
          { id: generateId(), text: '豊臣秀吉', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '徳川家康は関ヶ原の戦いに勝利した後、1603年に征夷大将軍に任命され江戸幕府を開きました。',
        imageUrl: null,
        order: 0,
      },
      {
        type: 'multiple-choice',
        text: '三代将軍・徳川家光が定めた、大名が1年おきに江戸と領地を行き来する制度は何ですか？',
        choices: [
          { id: generateId(), text: '参勤交代', isCorrect: true },
          { id: generateId(), text: '武家諸法度', isCorrect: false },
          { id: generateId(), text: '禁中並公家諸法度', isCorrect: false },
          { id: generateId(), text: '目安箱', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '参勤交代は、大名の経済力を削ぎ、幕府への反乱を防ぐ目的がありました。',
        imageUrl: null,
        order: 1,
      },
      {
        type: 'multiple-choice',
        text: '江戸時代、幕府がキリスト教を禁止するために、キリストやマリアの像を踏ませた行事は何ですか？',
        choices: [
          { id: generateId(), text: '絵踏（踏絵）', isCorrect: true },
          { id: generateId(), text: '宗門改', isCorrect: false },
          { id: generateId(), text: '檀家制度', isCorrect: false },
          { id: generateId(), text: '五人組', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '絵踏は、キリスト教徒を見つけ出すための手段として行われました。',
        imageUrl: null,
        order: 2,
      },
      {
        type: 'multiple-choice',
        text: '「享保の改革」を行い、目安箱の設置や公事方御定書を定めた八代将軍は誰ですか？',
        choices: [
          { id: generateId(), text: '徳川吉宗', isCorrect: true },
          { id: generateId(), text: '徳川綱吉', isCorrect: false },
          { id: generateId(), text: '徳川慶喜', isCorrect: false },
          { id: generateId(), text: '徳川家斉', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '徳川吉宗は「米将軍」とも呼ばれ、幕府の財政再建に努めました。',
        imageUrl: null,
        order: 3,
      },
      {
        type: 'multiple-choice',
        text: '江戸時代中期、上方（京都・大坂）を中心に栄えた、町人の活気あふれる文化は何ですか？',
        choices: [
          { id: generateId(), text: '元禄文化', isCorrect: true },
          { id: generateId(), text: '化政文化', isCorrect: false },
          { id: generateId(), text: '桃山文化', isCorrect: false },
          { id: generateId(), text: '東山文化', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '元禄文化では、松尾芭蕉の俳諧や近松門左衛門の人形浄瑠璃などが有名です。',
        imageUrl: null,
        order: 4,
      },
      {
        type: 'multiple-choice',
        text: '江戸時代後期、江戸を中心に栄えた、皮肉や滑稽さを特徴とする文化は何ですか？',
        choices: [
          { id: generateId(), text: '化政文化', isCorrect: true },
          { id: generateId(), text: '元禄文化', isCorrect: false },
          { id: generateId(), text: '天平文化', isCorrect: false },
          { id: generateId(), text: '国風文化', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '化政文化では、葛飾北斎や歌川広重の浮世絵、伊能忠敬の日本地図などが生まれました。',
        imageUrl: null,
        order: 5,
      },
      {
        type: 'multiple-choice',
        text: '1853年、浦賀に黒船で来航し、幕府に開国を求めたアメリカの提督は誰ですか？',
        choices: [
          { id: generateId(), text: 'ペリー', isCorrect: true },
          { id: generateId(), text: 'ハリス', isCorrect: false },
          { id: generateId(), text: 'マッカーサー', isCorrect: false },
          { id: generateId(), text: 'シャクシャイン', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: 'ペリーの来航により、長年続いた「鎖国」が終わるきっかけとなりました。',
        imageUrl: null,
        order: 6,
      },
      {
        type: 'multiple-choice',
        text: '「解体新書」を出版し、蘭学の発展に貢献した人物は杉田玄白ともう一人は誰ですか？',
        choices: [
          { id: generateId(), text: '前野良沢', isCorrect: true },
          { id: generateId(), text: '本居宣長', isCorrect: false },
          { id: generateId(), text: '平賀源内', isCorrect: false },
          { id: generateId(), text: '緒方洪庵', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '杉田玄白と前野良沢は、オランダ語の解剖書「ターヘル・アナトミア」を翻訳しました。',
        imageUrl: null,
        order: 7,
      },
      {
        type: 'multiple-choice',
        text: '老中として「寛政の改革」を行い、厳しい倹約令を出した人物は誰ですか？',
        choices: [
          { id: generateId(), text: '松平定信', isCorrect: true },
          { id: generateId(), text: '田沼意次', isCorrect: false },
          { id: generateId(), text: '水野忠邦', isCorrect: false },
          { id: generateId(), text: '井伊直弼', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '松平定信は朱子学以外の講義を禁止するなど、保守的な政治を行いました。',
        imageUrl: null,
        order: 8,
      },
      {
        type: 'multiple-choice',
        text: '1867年、政権を朝廷に返した出来事を何といいますか？',
        choices: [
          { id: generateId(), text: '大政奉還', isCorrect: true },
          { id: generateId(), text: '王政復古の大号令', isCorrect: false },
          { id: generateId(), text: '廃藩置県', isCorrect: false },
          { id: generateId(), text: '明治維新', isCorrect: false },
        ],
        timeLimit: 20,
        points: 1000,
        explanation: '十五代将軍・徳川慶喜が大政奉還を行い、約260年続いた江戸幕府が幕を閉じました。',
        imageUrl: null,
        order: 9,
      },
    ],
  },
];
